; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG157256 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG157257 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157258 DB	'qRegisterNormalizedMetaType', 00H
$SG160524 DB	'%s', 00H
	ORG $+1
$SG157608 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG157609 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157610 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG157960 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG157961 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157962 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG158961 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG158962 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG158963 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG159350 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG159351 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159352 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Qt_Music@@3Uqt_meta_stringdata_Qt_Music_t@@B DD 0ffffffffH ; qt_meta_stringdata_Qt_Music
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	051H
	DB	074H
	DB	05fH
	DB	04dH
	DB	075H
	DB	073H
	DB	069H
	DB	063H
	DB	00H
	ORG $+7
?qt_meta_data_Qt_Music@@3QBIB DD 08H			; qt_meta_data_Qt_Music
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	ORG $+4
$SG159702 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+10
$SG159703 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159704 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG160054 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+2
$SG160055 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG160056 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG160523 DB	'invalid argument', 00H
	ORG $+15
$SG160525 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.28.29910\include\xmemory', 00H
	ORG $+8
$SG160526 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '8', 00H, '.', 00H, '2', 00H, '9', 00H
	DB	'9', 00H, '1', 00H, '0', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG160527 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG160528 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+10
$SG160584 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.28.29910\include\xlocale', 00H
$SG154317 DB	'E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qmetat'
	DB	'ype.h', 00H
	ORG $+10
$SG154318 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154319 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ	; Qt_Music::metaObject
PUBLIC	?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z		; Qt_Music::qt_metacast
PUBLIC	?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Qt_Music::qt_metacall
PUBLIC	?qt_static_metacall@Qt_Music@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Qt_Music::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QMainWindow::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>
PUBLIC	?staticMetaObject@Qt_Music@@2UQMetaObject@@B	; Qt_Music::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Qt_Music@@2UQMetaObject@@B DB 030H DUP (?) ; Qt_Music::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Qt_Music@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Qt_Music@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Qt_Music::staticMetaObject'', COMDAT
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 73
	sub	rsp, 40					; 00000028H
; Line 67
	lea	rcx, OFFSET FLAT:?staticMetaObject@Qt_Music@@2UQMetaObject@@B ; Qt_Music::staticMetaObject
	call	??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QMainWindow::staticMetaObject>
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Qt_Music@@3Uqt_meta_stringdata_Qt_Music_t@@B
	mov	QWORD PTR ?staticMetaObject@Qt_Music@@2UQMetaObject@@B+8, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_meta_data_Qt_Music@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Qt_Music@@2UQMetaObject@@B+16, rax
; Line 70
	lea	rax, OFFSET FLAT:?qt_static_metacall@Qt_Music@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Qt_Music::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Qt_Music@@2UQMetaObject@@B+24, rax
; Line 71
	mov	QWORD PTR ?staticMetaObject@Qt_Music@@2UQMetaObject@@B+32, 0
; Line 72
	mov	QWORD PTR ?staticMetaObject@Qt_Music@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@Qt_Music@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Qt_Music::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>, COMDAT
; File E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QMainWindow::staticMetaObject>, COMDAT
; File E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QMainWindow::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@Qt_Music@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Qt_Music::qt_static_metacall
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 59
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 64
	ret	0
?qt_static_metacall@Qt_Music@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Qt_Music::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Qt_Music::qt_metacall
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 90
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 91
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 92
	mov	eax, DWORD PTR _id$[rsp]
; Line 93
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Qt_Music@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Qt_Music::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z PROC		; Qt_Music::qt_metacast
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 82
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 83
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 84
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Qt_Music@@3Uqt_meta_stringdata_Qt_Music_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 85
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 86
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 87
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Qt_Music@@UEAAPEAXPEBD@Z ENDP		; Qt_Music::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ PROC	; Qt_Music::metaObject
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 77
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 78
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Qt_Music@@2UQMetaObject@@B ; Qt_Music::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 79
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Qt_Music@@UEBAPEBUQMetaObject@@XZ ENDP	; Qt_Music::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File E:\vs_qt\5.14.2\5.14.2\msvc2017_64\include\QtCore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 96
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File F:\code\vs_project\Qt_Music\x64\Debug\moc\moc_Qt_Music.cpp
; Line 96
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
